version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5431:5431"
    volumes:
      - "./dumps:/dumps"
      - db-postgres:/var/opt/postgres

volumes:
  db-postgres: